<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:pay="urn:campuseats:payments"
    targetNamespace="urn:campuseats:payments"
    name="PaymentsService">



    <wsdl:types>

        <xsd:schema
            targetNamespace="urn:campuseats:payments">

            <xsd:element name="charge">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element
                            name="cardToken"
                            type="xsd:string"/>

                        <xsd:element
                            name="amount"
                            type="xsd:decimal"/>

                        <xsd:element
                            name="currency"
                            type="xsd:string"/>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="chargeResult">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element
                            name="transactionId"
                            type="xsd:string"/>

                        <xsd:element
                            name="status"
                            type="xsd:string"/>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:schema>

    </wsdl:types>


    <wsdl:message name="chargeRequest">

        <wsdl:part
            name="body"
            element="pay:charge"/>

    </wsdl:message>


    <wsdl:message name="chargeResponse">

        <wsdl:part
            name="body"
            element="pay:chargeResult"/>

    </wsdl:message>



    <wsdl:portType name="Payments">

        <wsdl:operation name="charge">

            <wsdl:input
                message="pay:chargeRequest"/>

            <wsdl:output
                message="pay:chargeResponse"/>

        </wsdl:operation>

    </wsdl:portType>




    <wsdl:binding
        name="PaymentsSOAP"
        type="pay:Payments">

        <soap:binding
            transport="http://schemas.xmlsoap.org/soap/http"
            style="document"/>

        <wsdl:operation name="charge">

            <soap:operation
                soapAction="urn:campuseats:payments/charge"/>

            <wsdl:input>

                <soap:body
                    use="literal"/>

            </wsdl:input>

            <wsdl:output>

                <soap:body
                    use="literal"/>

            </wsdl:output>

        </wsdl:operation>

    </wsdl:binding>



    <wsdl:service name="PaymentsService">

        <wsdl:port
            name="PaymentsSOAP"
            binding="pay:PaymentsSOAP">

            <soap:address
                location="https://api.unipay.example/pay"/>

        </wsdl:port>

    </wsdl:service>

</wsdl:definitions>